version: '3.8'

services:
  server:
    build: src
    restart: always
    command: >
      sh -c "cd app &&
             uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 80"
    env_file:
      - ./.env
    ports:
      - "80:80"
